//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inven2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos
    {
        public int IdAsientoCont { get; set; }
        public string Descripción { get; set; }
        public Nullable<int> Id_tipoIvent { get; set; }
        public string Cuenta_contable { get; set; }
        public Nullable<int> Id_tipo_cuenta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Tipo_Cuenta Tipo_Cuenta { get; set; }
        public virtual Tipo_Inventario Tipo_Inventario { get; set; }
    }
}
