//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inven2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INVENTARIODBEntities : DbContext
    {
        public INVENTARIODBEntities()
            : base("name=INVENTARIODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacenes> Almacenes { get; set; }
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Cuenta> Tipo_Cuenta { get; set; }
        public virtual DbSet<Tipo_Inventario> Tipo_Inventario { get; set; }
        public virtual DbSet<Asientos> Asientos { get; set; }
    }
}
