//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inven2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Inventario()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int Id_Tipo_inv { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cuenta_contable { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual Tipo_Cuenta Tipo_Cuenta { get; set; }
    }
}
